### ISSUE TITLE
file.use is not a function

### ISSUE THREAD

**Issue by carstenbaumhoegger** [etchteam/storybook-addon-css-variables-theme#12] opened 2022-03-21 10:53 UTC
Hey there,

thanks for this helpful extension!

We've been using it with a project based on Nx 11 and everything was working great for us.

We've now updated the project to Nx 13 and we're getting this error:
![image](https://user-images.githubusercontent.com/4333261/159245952-458016ff-4f2b-4cb1-a474-5d957f0794ed.png)

We're using this preview.js-config:
```
import gray from '!style-loader?injectType=lazyStyleTag!css-loader!../libs/ui/assets/styles/themes/lazy.gray.css';
import blue from '!style-loader?injectType=lazyStyleTag!css-loader!../libs/ui/assets/styles/themes/lazy.blue.css';
import { setCompodocJson } from '@storybook/addon-docs/angular';
import docJson from '../documentation.json';
import 'cypress-storybook/angular';
import cssVariablesTheme from '@etchteam/storybook-addon-css-variables-theme';
import { addDecorator } from '@storybook/angular';

export const decorators = [cssVariablesTheme];
setCompodocJson(docJson);
addDecorator(cssVariablesTheme);
const customViewports = {
 ...
};

export const parameters = {
  options: {
    storySort: {
        ...
    },
  },
  viewport: { viewports: customViewports },
  cssVariables: {
    files: {
      'Theme gray': gray,
      'Theme blue': blue
    },
  },
};
```

The generated code looks like it loads a simple string, so we assume `file.use` isn't accessible because of that
![MicrosoftTeams-image](https://user-images.githubusercontent.com/4333261/159246810-e421a48c-b436-45d6-aed8-f9aba479646d.png)

Do you have any idea, why this is happening?
Storybook itself is fine but the addon isn't working for us anymore.

**Comment by YasinKuralay** [comment] 2022-04-14 14:25
Hey @gavmck  we have the same problem. We weren't using the addon before though. Our nx version is currently 13.9.5.

I'm assuming you want to know what the variable is when printed without the addon code? When I console.log it I get the following output. Let me know if you need anything else from me: 

`
      var exported = {};

      import API from "!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
      import domAPI from "!../node_modules/style-loader/dist/runtime/styleDomAPI.js";
      import insertFn from "!../node_modules/style-loader/dist/runtime/insertBySelector.js";
      import setAttributes from "!../node_modules/style-loader/dist/runtime/setAttributesWithoutAttributes.js";
      import insertStyleElement from "!../node_modules/style-loader/dist/runtime/insertStyleElement.js";
      import styleTagTransformFn from "!../node_modules/style-loader/dist/runtime/styleTagTransform.js";
      import content, * as namedExport from "!!../node_modules/css-loader/dist/cjs.js!./styles.c017.css";
      
      if (content && content.locals) {
              exported.locals = content.locals;
            }
            

var refs = 0;
var update;
var options = {};

options.styleTagTransform = styleTagTransformFn;
options.setAttributes = setAttributes;

      options.insert = insertFn.bind(null, "head");
    
options.domAPI = domAPI;
options.insertStyleElement = insertStyleElement;

exported.use = function(insertOptions) {
  options.options = insertOptions || {};

  if (!(refs++)) {
    update = API(content, options);
  }

  return exported;
};
exported.unuse = function() {
  if (refs > 0 && !--refs) {
    update();
    update = null;
  }
};


if (module.hot) {
  if (!content.locals || module.hot.invalidate) {
    var isEqualLocals = function isEqualLocals(a, b, isNamedExport) {
  if (!a && b || a && !b) {
    return false;
  }

  var p;

  for (p in a) {
    if (isNamedExport && p === "default") {
      // eslint-disable-next-line no-continue
      continue;
    }

    if (a[p] !== b[p]) {
      return false;
    }
  }

  for (p in b) {
    if (isNamedExport && p === "default") {
      // eslint-disable-next-line no-continue
      continue;
    }

    if (!a[p]) {
      return false;
    }
  }

  return true;
};
    var isNamedExport = !content.locals;
    var oldLocals = isNamedExport ? namedExport : content.locals;

    module.hot.accept(
      "!!../node_modules/css-loader/dist/cjs.js!./styles.c017.css",
      function () {
        if (!isEqualLocals(oldLocals, isNamedExport ? namedExport : content.locals, isNamedExport)) {
                module.hot.invalidate();

                return;
              }

              oldLocals = isNamedExport ? namedExport : content.locals;

              if (update && refs > 0) {
                      update(content);
                    }
      }
    )
  }

  module.hot.dispose(function() {
    if (update) {
            update();
          }
  });
}


export * from "!!../node_modules/css-loader/dist/cjs.js!./styles.c017.css";
       export default exported;`

**Comment by gavmck** [comment] 2022-04-14 14:45
Huh, so it's the right code, but being imported as text instead of actual usable code.

**Comment by gavmck** [comment] 2022-04-14 15:27
I've managed to recreate this and it looks like it's probably an issue with NX. The css file is transformed properly by webpack to give you a bunch of JS with use/unuse functions, but something in there is loading it as text instead of javascript. The `!!` at the beginning should eject out of pre-set webpack loaders so I can only see that NX is doing something magic.

**Comment by YasinKuralay** [comment] 2022-04-14 15:40
Ah okay, so the problem is not the addon. I ll see what I can find/do, thank you very much for the help :)

**Comment by llaenowyd** [comment] 2022-05-12 19:28
I got a similar error not with Nx but trying this,

Library package exports styles `styles/light-theme.css`, `styles/dark-theme.css` and these files look like e.g.

```css
:root {
  --bg-control: #93c5fd;
  --bg-control-disabled: #d1d5db;
  --text-control: #075985;
  --text-control-disabled: #6b7280;
  --color-shadow: #9ca3af;
}
```

Then Storybook is added to a separate application package that depends on the library, and  the Storybook `preview.js` says

```js
import lightTheme from '@a110/rito/styles/light-theme'
import darkTheme from '@a110/rito/styles/dark-theme'
// ...
  cssVariables: {
    files: {
      'Dark Theme': darkTheme,
      'Light Theme': lightTheme,
    },
    defaultTheme: 'Light Theme',
  },
```

The idea is that the library would export some styles (just css variables) that are usable for dark and light mode. Then secondly the Storybook is just showing the library rather than adding anything more, styles or components.

Probably this isn't working because I didn't follow the instructions - I'm not using an inline style loader, and the variables are placed in a `:root` selector... But the error seems similar,

```
index.js:42 Uncaught (in promise) TypeError: file.use is not a function
    at _callee$ (index.js:42:20)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at asyncGeneratorStep (index.js:22:99)
    at _next (index.js:24:194)
    at index.js:24:364
    at new Promise (<anonymous>)
    at index.js:24:97
    at addBrandStyles (index.js:29:26)
```

**Comment by Nighink** [comment] 2022-08-18 12:11
I had the same problem with a new Angular 13 project. There is a stackoverflow post that proposes to use some special syntax for imports, which at least gave me an object instead of a string though it is still not working. See https://stackoverflow.com/questions/69614700/import-css-file-into-es6-returns-string-instead-of-object/69661939#69661939

The import I tried was `import base from 'test.css.webpack[javascript/auto]!=!!!style-loader?injectType=lazyStyleTag!css-loader!../projects/path/to/base.css';` I looked at the object loaded in the browser developer console and found that I can call `use()` to add a style to the storybook iframe though the style's content was some javascript containing a string. 

In the end, it works for me to skip the css-loader
```
import base from 'test.css.webpack[javascript/auto]!=!!!style-loader?injectType=lazyStyleTag!../projects/path/to/base.css';
```
or
```
import base from 'test.scss.webpack[javascript/auto]!=!!!style-loader?injectType=lazyStyleTag!sass-loader!../projects/path/to/_base.scss';
```

I spent far too much time experimenting with this. I hope it helps someone.

**Comment by DanWebb** [comment] 2022-11-24 12:39
The issue seems to be that some kind of transformation is happening to the css/scss file before the inline loader ever runs.

To workaround that, one way would be to rename the files extension, to avoid affecting any actual project files, a separate file could be created that imports the styles for the theme, so:

```
- .storybook/
   | - themes/
   |   | - dark.scss.theme
   | - preview.js
```

Then in `dark.scss.theme` the actual file from the project could be imported `@import '../../src/styles/themes/dark';`.

Then the loader can be applied as usual, pointing to the new file:

```
import dark from '!!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!./styles/dark.scss.theme';
```

The key is in renaming the files extension to something like `.scss.whatever` – this avoids any existing configuration applying to .scss files in the codebase.

---

I'm going to close this issue, because it appear to be down to specific webpack/project configurations.

**Closed by DanWebb** 2022-11-24 12:39 UTC
Labels: bug, help wanted
